// Generates src/generated/html-to-image.ts from the installed package, so the version stays pinned in
// package.json rather than checked in as a blob. Runs before dev and build.
//
// It is generated as a *string* rather than copied into public/ because of where it has to run:
// the gallery snapshot code executes inside the sandboxed, opaque-origin frame that a student's
// work is served into (see src/lib/gallery.ts). Such a frame cannot fetch a script from us at all
// — the request is refused — so the library has to travel inside the document itself.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "src", "generated");

const source = await readFile(require.resolve("html-to-image/dist/html-to-image.js"), "utf8");
const { version } = require("html-to-image/package.json");

await mkdir(target, { recursive: true });
await writeFile(join(target, "html-to-image.ts"), [
  `// Generated by scripts/vendor-assets.mjs from html-to-image@${version} (MIT). Do not edit.`,
  `export const HTML_TO_IMAGE_VERSION = ${JSON.stringify(version)};`,
  `export const HTML_TO_IMAGE_SOURCE = ${JSON.stringify(source)};`,
  "",
].join("\n"));
console.log(`generated src/generated/html-to-image.ts from html-to-image@${version}`);
